[workspace]
projects = [
    "Common",
    "Passive Sensing",
    "Critical Slowing Down",
    "Unique Places",
    "Crowded Places",
    "Home Stay",
    "Emotional Inertia",
    "Weather",
    "Dimensional",
    "Hidden Markov",
    "Sleep",
    "Circadian Rhythm"
]
